/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "hook.h"
#include "my_getcontext.h"
#include "libunwind.h"

#include <android/log.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include <dlfcn.h>
#include <sys/syscall.h>
/* Header for class com_iexin_common_CrashHelper */

#ifndef _Included_com_iexin_common_CrashHelper
#define _Included_com_iexin_common_CrashHelper
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
